# Generated by Django 5.1.2 on 2024-11-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_remove_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highestbid',
            field=models.FloatField(default=0),
        ),
    ]
