# Generated by Django 5.1.2 on 2024-11-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_userprofile_highestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cooldown',
            field=models.IntegerField(default=0),
        ),
    ]
