# Generated by Django 5.1.2 on 2024-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0004_userprofile_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='highestbid',
            field=models.IntegerField(default=0),
        ),
    ]
