# Generated by Django 5.1.2 on 2024-12-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0005_alter_userprofile_highestbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='highestbid',
        ),
    ]
