# Generated by Django 5.1.2 on 2024-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0006_remove_userprofile_highestbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cooldown',
            field=models.IntegerField(default=3),
        ),
    ]
