# Generated by Django 5.1.2 on 2024-11-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_image_url2_product_image_url3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.AddField(
            model_name='product',
            name='highest_bid',
            field=models.FloatField(default=0),
        ),
    ]
