# Generated by Django 5.1.2 on 2024-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_bid_bid_time_product_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_price',
            field=models.IntegerField(),
        ),
    ]
