# Generated by Django 5.1.2 on 2024-12-02 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_brand_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='startdt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
