# Generated by Django 5.1.2 on 2024-12-02 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0006_remove_userprofile_highestbid'),
        ('Products', '0007_alter_bid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.userprofile'),
        ),
    ]
