# Generated by Django 5.1.2 on 2024-12-02 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0006_remove_userprofile_highestbid'),
        ('Products', '0008_alter_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authenticate.userprofile'),
        ),
    ]
