# Generated by Django 5.1.2 on 2024-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest_bid',
            field=models.IntegerField(default=models.F('starting_price')),
        ),
    ]
