# Generated by Django 5.1.2 on 2024-12-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_bid_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mailsent',
            field=models.BooleanField(default=False),
        ),
    ]
